---
title: "Analysis of College Majors and Impact on Employment"
author: "Arona Cho, Irene Jo, Melanie Kuo"
date: "Autumn 2022"
affilication: "INFO-201: Technical Foundations of Informatics - The Information School - University of Washington"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Abstract: 
Our main concern for this project is to find the relationships between various college majors, employment and salary as well as graduation rates. This is important information since this can be used to further predict future supply of workers in various fields as well as the demands of various job fields. To address this, we will provide large amounts of data on employment and unemployment rates, median salary, number of graduates and gender distribution across 173 college majors surveyed in the American Community Survey 2010-2012 Public Use Microdata Series.

### Keywords: 

College majors, employment, unemployment, salary, age/gender

### Introduction: 

For our project, we are analyzing hundreds of different college majors and their correlation to employment and unemployment. The categories we analyze are divided by age (all ages, under 28, and over 25), and we also will take a look at basic earnings and sex. Our goal is to determine whether or not one’s major has any impact on their future employment. The FiveThirtyEight article “The Economic Guide to Picking a Major” uses this dataset to demonstrate the importance behind picking a major: “A college degree is no guarantee of economic success. But through their choice of major, they can take at least some steps toward boosting their odds” (Casselman). We want to assess if majors are truly as important as perceived, and if majoring in something that may be perceived to have a low or high employment rate may actually turn out to have a different or unexpected outcome.

### Problem Domain:

Our project frame is finding employment and unemployment rates as well as rates of graduation and gender distribution within the 173 majors. With this information, we hope to discover various trends and patterns that can be further utilized to predict future job market changes as well as to inform students tasked with making decisions that will have long lasting effects in their lives. 

The human values that we took into consideration while working on this project were the long term effects of making these conclusions from this data collected in American Community Survey 2010-2012, as we could end up discouraging some people from certain job fields and causing a shift in supply of certain college major graduates in the job field. To avoid spreading inaccurate information, we made sure to draw accurate conclusions from reliable and quantitative data and utilizing analytic methods to make accurate conclusions. 

Direct stakeholders of this project include us, the authors, as we would like to make sure it includes accurate, reliable, and useful information. If we cannot deliver information that does not meet those requirements, then we would fail to meet our objective of assessing the importance of the type of college major in relation to other factors such as employment rate and gender distribution. Other direct stakeholders for this project are the future and current college enrollees that would benefit from our assessment of college majors. The Federal Reserve Bank of New York reported that there is currently a growing wage gap between those without a college degree and those with a college degree (The Federal Reserve Bank of New York). People that consider income to be crucial to their choice of major would be one of the main stakeholders of this project. Possible indirect stakeholders could be the institutions that facilitate and educate people that would like to pursue college degrees, as well as employers and the fields of the different majors listed in this project. 

Possible harms of this project include biases and reinforcement of stereotypes that may be formed regarding specific majors. Through the analysis of this project, there may be data conclusions that are unexpected, such as seemingly high-paying majors not paying as much, or vice versa. The analysis of this data could possibly affect one’s decision of what to major in college, which can be both a harm or benefit. One may choose a specific major due to factors like income or employment rates, so this information can be useful to some, and may provide benefits by assisting with these types of decisions. It’s also important to know information regarding the amount of women in certain fields in order to assess areas where more gender diversity is needed. According to the National Girls Collaborative Project, women make up only 34% of the STEM workforce (National Girls Collaborative Project). This means that many progressions need to be made towards closing the gender gap, and using this data is a great start. 

### Research Questions
#### _What are the median wages of college graduates with different majors?_
Finding the median wages of college graduates with various majors can help students get a better understanding of levels of financial success of graduates with different majors and help them make a decision that best matches their dreams. It can also be used for those in specific majors to estimate their future wage and calculate their financial status. 

#### _Which college majors result in higher rates of employment and salary?_
This data helps identify different patterns in growing and shrinking fields of study to be used to further predict the job market changes as well as assist students that have to choose a major by providing important information of employment and salary rates. 

#### _What are the relationships between gender and college majors?_
This information is important since it helps data about gender inequality and distribution amongst the different majors easier to view and understand. This allows us to discover which majors are preferred by different genders and possibly carry on further research about why.

#### _How do the graduation rates of each major compare to others?_
It is important because it can be informative for those going into the major and those that are choosing majors to take into consideration the rates of graduation based on academic rigor, lack of employment offers or overall bad staff. This information is needed to help the school make improvements or assistance for students in majors with very low graduation rates or etc. 

### The Dataset
Our dataset showcases information regarding various majors and their statistics for employment, graduation rates, and gender. From viewing this dataset, we can identify correlations between the data, and determine whether or not these factors have impacts on one another. Additionally, the dataset has a vast amount of information, which is useful for those who may be interested in finding a less popular major or specific, researched statistics regarding another specific major. 


---
##### Table 1. Summary of the dataset.
|Data File| Num of observations (row)| Num of var (col)|
|---------| ----------------------|------------------|
|All-ages|173|10|
|Grad-students|173|10|
|Majors-list|174|3|
|Recent-grades|173|10|
|Women-stem|76|9|

###### Tunguz, Bojan. All-ages (Data set), 2020.
https://www.kaggle.com/datasets/tunguz/college-majors?select=all-ages.csv

###### Tunguz, Bojan. Grad-students (Data set), 2020.
https://www.kaggle.com/datasets/tunguz/college-majors?select=grad-students.csv

###### Tunguz, Bojan. Majors-list (Data set), 2020.
https://www.kaggle.com/datasets/tunguz/college-majors?select=majors-list.csv

###### Tunguz, Bojan. Recent-grads (Data set), 2020.
https://www.kaggle.com/datasets/tunguz/college-majors?select=recent-grads.csv

###### Tunguz, Bojan. Women-stem (Data set), 2020.
https://www.kaggle.com/datasets/tunguz/college-majors?select=women-stem.csv

### Provenance
This data was collected in 2020 by Bojan Tunguz, a data scientist from Indiana. While there is little information regarding the purpose behind the collection of the dataset, Tunguz has compiled hundreds of datasets regarding a wide variety of topics and has an extremely high ranking with Kaggle, and one can infer that his purpose behind this data collection was pure interest regarding the topic at hand. Tunguz used the American County Survey 2010-2012 for statistics behind these majors.

The data collection effort of the American County Survey of 2010-2012 was federally funded as the data was obtained from the U.S. Census. For Tunguz, they were able to collect the data through public sources as listed on the U.S. Census Bureau website. Those that have an interest in a specific major’s post-graduate employment rate would most likely benefit from this data. Financially, people who are researching for the purpose of finding which major would have the highest employment rate for their career would most likely benefit. 

The data was validated and held secure by its source of collection, which is the U.S. Census Bureau. The residents that complete the survey are required by law to accurately respond, while the U.S. Census Bureau is held by the law to keep the information confidential. As it is a government survey, it is held as a credible source as it should be an accurate reflection of the state of residents of the United States. However, due to the census data being self-reported, there may be response bias present in the data. 

Through Kaggle, a platform that allows for the publishing and sharing of datasets, we searched for datasets regarding college majors as our key interest. Through there, we found this dataset and found the contents of it interesting as it specifically included the statistics of women in STEM. As all three of us are women in STEM, we decided to choose this dataset because of its relevance to our personal career goals and aspirations. We do credit the source of the data, Bojan Tunguz, by the citations done above. 

### Expected Implications
Expected implications for technologists and designers include the usage of employment data to guide their future career paths. This data can help those that would like to work in the field of technology and design to decision-make which major would be the most beneficial for their own situation. The data regarding females in STEM may deter or attract certain genders in the future from going down various major paths. Additionally, there may be a rise in interest for certain majors among technologists and designers depending on the employment rate. Generally, the patterns that the dataset provides about college majors and their relation to employment can allow for future policies to be made to support those with unequal or unfair opportunities. From a gender studies view, policymakers can use this data to make future regulations and infrastructure for gender minorities in select majors such as STEM. 

### Limitations
A few limitations for this project include the fact that not all majors can be addressed, especially as majors become more varied and unique. For instance, the “Other Foreign Languages” category is a bit broad, as there’s no specification as to what the foreign languages studied are, and subsequently, the data for this specific topic may end up being generalized.
Additionally, the data is only updated every two years, so there is likely more information that has changed or may be slightly outdated, especially with the uncertainty factor of the pandemic that took effect. Lastly, the correlation between majors and employment may not be exact. Some face unemployment due to reasons far beyond what they majored in, and it’s difficult to gauge reasoning for these circumstances from viewing a dataset. For this reason, it’s extremely important to remember to view this data with an open perspective and use it for the purposes of learning.

### References
 Bencasselman. “The Economic Guide to Picking a College Major.” FiveThirtyEight, FiveThirtyEight, 12 Sept. 2014, https://fivethirtyeight.com/features/the-economic-guide-to-picking-a-college-major/. 
 
 “The Labor Market for Recent College Graduates.” Federal Reserve Bank of New York, 2021, https://www.newyorkfed.org/research/college-labor-market/college-labor-market_wages.html 
 
  “State of Girls and Women in Stem.” National Girls Collaborative Project, 28 February 2022, https://ngcproject.org/resources/state-girls-and-women-stem. 

